### PR TITLE
V2-1367 Created event listener

### PR DESCRIPTION
**Pull request by dmitryChernukh**
This change is [Reviewable](https://reviewable.io/reviews/lancastersolutions/rsqueuebundle/6)

### CODE REVIEW

**Comment by lazer1988** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6)*

**Comment by JanisGruzis** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Listeners/ConsumerListener.php, line 25 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6#-Knj9ZibpkFXEc_6zYOb:-Knj9ZibpkFXEc_6zYOc:b-9pt1el) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/ef2570825d68fbec597b1477232ccff491edf0b6/Listeners/ConsumerListener.php#L25)):*
> ```PHP
>      * @param $doctrine
>      */
>     public function __construct($doctrine)
> ```

Use typehing RegistryInterface. Call variable $registry from now on. We dont use $doctrine because that allows flexibility in case if we choose to use other manager registry instead of doctrine like propel etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6)*

**Comment by dimaotm** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6)*

**Comment by dmitryChernukh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Listeners/ConsumerListener.php, line 25 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6#-Knj9ZibpkFXEc_6zYOb:-KnndVDBjMvWjgS3da7g:b-8m7c8e) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/ef2570825d68fbec597b1477232ccff491edf0b6/Listeners/ConsumerListener.php#L25)):*
<details><summary><i>Previously, JanisGruzis (Jānis Gruzis) wrote…</i></summary><blockquote>

Use typehing RegistryInterface. Call variable $registry from now on. We dont use $doctrine because that allows flexibility in case if we choose to use other manager registry instead of doctrine like propel etc.
</blockquote></details>

I use Doctrine\Common\Persistence\ManagerRegistry interface

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6)*

**Comment by JanisGruzis** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/6)*

**Pull request merged**
