### PR TITLE
V2-1073

### PR DESCRIPTION
**Pull request by JanisGruzis**
This change is [Reviewable](https://reviewable.io/reviews/lancastersolutions/rsqueuebundle/3)

### CODE REVIEW

**Comment by morkers** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Exception/LockException.php, line 13 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak34mfaFkiB64JG_gD:-Kak34mfaFkiB64JG_gE:bumkd8d) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Exception/LockException.php#L13)):*
> ```PHP
> {
> 
> }
> ```

Nwe line

---

*[Services/LockHandler.php, line 103 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak3Uu5yvUhWLt1u9ut:-Kak3Uu5yvUhWLt1u9uu:b-508e6g) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Services/LockHandler.php#L103)):*
> ```PHP
>     {
>         $content = json_encode([
>             'pid' => getmypid(),
> ```

What if process dies and diferent process is created with the same pid?

---

*[Services/LockHandler.php, line 110 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak3RKeL8akDuUtrXXC:-Kak3RKeL8akDuUtrXXD:b-byfdrb) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Services/LockHandler.php#L110)):*
> ```PHP
>         }
>     }
> }
> ```

New line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3)*

**Comment by JanisGruzis** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Exception/LockException.php, line 13 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak34mfaFkiB64JG_gD:-Kakzh6CGObTClDEChNO:b-896fix) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Exception/LockException.php#L13)):*
<details><summary><i>Previously, morkers (Matīss Lulle) wrote…</i></summary><blockquote>

Nwe line
</blockquote></details>

Done.

---

*[Services/LockHandler.php, line 103 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak3Uu5yvUhWLt1u9ut:-KakzjMfuKAwk8VnNRf5:b-896fix) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Services/LockHandler.php#L103)):*
<details><summary><i>Previously, morkers (Matīss Lulle) wrote…</i></summary><blockquote>

What if process dies and diferent process is created with the same pid?
</blockquote></details>

Done.

---

*[Services/LockHandler.php, line 110 at r1](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-Kak3RKeL8akDuUtrXXC:-KakzkRIH_ONJMTh3WZ4:b-896fix) ([raw file](https://github.com/lancastersolutions/rsqueuebundle/blob/4f24c52d2cefdbf617643cc0ec489fa61a0e16de/Services/LockHandler.php#L110)):*
<details><summary><i>Previously, morkers (Matīss Lulle) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3)*

**Comment by morkers** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3#-:-Kal-FmIjxnqvnI7L-0W:bnfp4nl)*

**Comment by morkers** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lancastersolutions/rsqueuebundle/3)*

**Pull request merged**
